spring:
  application:
    name: driver-service
  config:
    import: "optional:configserver:http://localhost:8888"
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:redis123}
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true
        spring.json.type.mapping: >
          driver-status:iuh.fit.driverservice.dto.event.DriverStatusEvent,
          driver-accepted:iuh.fit.driverservice.dto.event.DriverAcceptedEvent,
          driver-rejected:iuh.fit.driverservice.dto.event.DriverRejectedEvent
