server:
  port: 8080

spring:
  application:
    name: api-gateway

  data:
    redis:
      host: redis
      port: 6379
      password: redis123
      timeout: 2000ms

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        # route-level RequestRateLimiter
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                # nổ” tối đa 2 request ngay lúc đầu, sau đó mỗi giây hồi lại 1 request.
                redis-rate-limiter.burstCapacity: 2
                key-resolver: "#{@ipKeyResolver}"

        # route-level RequestRateLimiter
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**

        # Socket.IO WebSockets Route
        - id: notification-service-websocket
          uri: ws://notification-service:9093
          predicates:
            - Path=/socket.io/**

        # Socket.IO HTTP Polling Fallback
        - id: notification-service-socketio-http
          uri: http://notification-service:9093
          predicates:
            - Path=/socket.io/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**,/api/admin/users/**

        - id: driver-service
          uri: lb://driver-service
          predicates:
            - Path=/api/drivers/**,/api/admin/drivers/**

        - id: review-service
          uri: lb://review-service
          predicates:
            - Path=/api/reviews/**

        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/api/v1/bookings/**

        - id: ride-service
          uri: lb://ride-service
          predicates:
            - Path=/api/v1/rides/**

        - id: pricing-service
          uri: lb://pricing-service
          predicates:
            - Path=/api/pricing/**

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payments/**

        - id: ai-scoring-service
          uri: http://cab-ai-scoring-service:8000
          predicates:
            - Path=/api/v1/ai/**

      default-filters:
        - name: Retry
          args:
            retries: 1
            series: SERVER_ERROR

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    iuh.fit.api_gateway: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 30
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}:${random.value}
