server:
  port: 8080

spring:
  application:
    name: api-gateway

  data:
    redis:
      host: redis
      port: 6379
      password: redis123
      timeout: 2000ms

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        # route-level RequestRateLimiter
        - id: auth-service
          uri: http://auth-service:8081
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                # nổ” tối đa 2 request ngay lúc đầu, sau đó mỗi giây hồi lại 1 request.
                redis-rate-limiter.burstCapacity: 2
                key-resolver: "#{@ipKeyResolver}"

        # route-level RequestRateLimiter
        - id: eta-service
          uri: http://eta-service:8082
          predicates:
            - Path=/api/eta/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                key-resolver: "#{@ipKeyResolver}"

      default-filters:
        - name: Retry
          args:
            retries: 1
            series: SERVER_ERROR

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    iuh.fit.api_gateway: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 30
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}:${random.value}
