server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: ${AUTH_DB_JDBC_URL}
    username: ${AUTH_DB_USER}
    password: ${AUTH_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# ĐƯA EUREKA RA NGOÀI, KHÔNG NẰM TRONG SPRING
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}:${random.value}