server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: ${AUTH_DB_JDBC_URL:jdbc:postgresql://localhost:5433/auth_db}
    username: ${AUTH_DB_USER:admin}
    password: ${AUTH_DB_PASSWORD:adminpassword}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# ĐƯA EUREKA RA NGOÀI, KHÔNG NẰM TRONG SPRING
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}:${random.value}

auth:
  jwt:
    access-token-minutes: ${AUTH_ACCESS_TOKEN_MINUTES:120}
    refresh-token-days: ${AUTH_REFRESH_TOKEN_DAYS:30}

integration:
  email-service:
    url: ${EMAIL_SERVICE_URL:http://email-service:8087}
