server:
  port: 8083

spring:
  application:
    name: driver-service
  datasource:
    url: ${DRIVER_DB_JDBC_URL:jdbc:postgresql://localhost:5435/driver_db}
    username: ${DRIVER_DB_USER:admin}
    password: ${DRIVER_DB_PASSWORD:adminpassword}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:redis123}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://eureka-server:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}:${random.value}
