server:
  port: 8086

spring:
  data:
    mongodb:
      uri: mongodb://mongodb:27017/review_db

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
