server:
  port: ${REVIEW_SERVICE_PORT:8086}

spring:
  data:
    mongodb:
      uri: mongodb://mongodb:27017/review_db
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    consumer:
      group-id: review-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: >
          ride-created:java.util.Map,
          ride-cancelled:java.util.Map,
          ride-accepted:java.util.Map,
          booking-timeout:java.util.Map,
          ride-finished:java.util.Map,
          ride-started:java.util.Map,
          driver-arrived:java.util.Map,
          ride-assigned:java.util.Map

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
