server:
  port: 8082

spring:
  application:
    name: user-service
  datasource:
    url: ${USER_DB_JDBC_URL:jdbc:postgresql://localhost:5434/user_db}
    username: ${USER_DB_USER:admin}
    password: ${USER_DB_PASSWORD:adminpassword}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://eureka-server:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}:${random.value}
