momo:
  environment: dev
  notifyUrl: ${MOMO_NOTIFY_URL:https://example.com/api/payments/momo/ipn}
  returnUrl: ${MOMO_RETURN_URL:https://example.com/payment-result}
  lang: vi
  partnerName: CAB Booking
  storeId: CAB_BOOKING

zalopay:
  endpoint: ${ZALOPAY_ENDPOINT:https://sb-openapi.zalopay.vn/v2}
  callbackUrl: ${ZALOPAY_CALLBACK_URL:https://example.com/api/payments/zalopay/callback}
  redirectUrl: ${ZALOPAY_REDIRECT_URL:https://example.com/payment-result}

vnpay:
  paymentUrl: ${VNPAY_PAYMENT_URL:https://sandbox.vnpayment.vn/paymentv2/vpcpay.html}
  tmnCode: ${VNPAY_TMN_CODE:TL1HKBCX}
  hashSecret: ${VNPAY_HASH_SECRET:A6GA3NSBPW7ZE1P3R1KRZKESNELHRTY3}
  returnUrl: ${VNPAY_RETURN_URL:https://scratch-heaving-create.ngrok-free.dev/api/payments/vnpay/return}
  ipnUrl: ${VNPAY_IPN_URL:https://scratch-heaving-create.ngrok-free.dev/api/payments/vnpay/ipn}
  bankCode: ${VNPAY_BANK_CODE:NCB}
