server:
  port: 8086

spring:
  application:
    name: matching-service

  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        # MATCHING LÀ NGƯỜI PHÁT RA RIDE-ASSIGNED
        spring.json.type.mapping: >
          ride-assigned:com.cab.matching.core.dto.event.outbound.DriverMatchedEvent
    consumer:
      group-id: matching-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.cab.matching.core.dto.event.inbound.RideCreatedEvent
        spring.json.type.mapping: >
          ride-created:com.cab.matching.core.dto.event.inbound.RideCreatedEvent

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:${EUREKA_SERVER_URL:http://localhost:8761/eureka/}}
    register-with-eureka: true
    fetch-registry: true
