services:
  api-gateway:
    build:
      context: ..
      dockerfile: ./api-gateway/Dockerfile
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - SPRING_APPLICATION_NAME=api-gateway
    volumes:
      - maven-cache:/root/.m2
    networks:
      - cab-network
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy

volumes:
  maven-cache:
    driver: local
