services:
  review-service:
    build:
      context: ..
      dockerfile: ./review-service/Dockerfile
    container_name: review-service
    ports:
      - "8086:8086"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/review_db
    volumes:
      - maven-cache:/root/.m2
    networks:
      - cab-network
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
      mongodb:
        condition: service_started

volumes:
  maven-cache:
    driver: local

networks:
  cab-network:
    driver: bridge
