name: cab-booking-system

include:
  - config-server/docker-compose.yaml
  - eureka/docker-compose.yaml
  - api-gateway/docker-compose.yaml
  - auth-service/docker-compose.yaml

volumes:
  maven-cache:
    driver: local

networks:
  cab-network:
    driver: bridge