services:
#Auth
  auth_service:
    build:
      context: .
      dockerfile: service/auth_service/Dockerfile
    container_name: auth_service
    ports:
      - "8081:8081"
    env_file:
      - ./service/auth_service/.env
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - cab-net
    depends_on:
      auth_db:
        condition: service_healthy

  auth_db:
    image: mariadb:11
    container_name: auth_db
    ports:
      - "3307:3307"
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=auth_db
    networks:
      - cab-net
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - auth_db_data:/var/lib/mysql
# hết phần auth


volumes:
  auth_db_data:

networks:
  cab-net:
    driver: bridge