spring:
  application:
    name: auth-service # Tên này phải khớp với tên file trên Config Server
  config:
    import: "optional:configserver:http://config-server:8888" # Gọi đến server để lấy toàn bộ config về