server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
#    cho auth db chạy ở port 3307 để tránh xung đột với mariadb trên máy
#  nếu muốn chạy bằng intellij nhớ chỉnh lại thafnh 3306 để  connect vô máy của mình
#    Còn trong docker để là 3307
    url: ${SPRING_DATASOURCE_URL:jdbc:mariadb://localhost:3307/auth_db?createDatabaseIfNotExist=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 2
      max-lifetime: 600000
      keepalive-time: 300000
      validation-timeout: 5000

  jpa:
    database-platform: ${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.MariaDBDialect}
    properties:
      hibernate:
        dialect: ${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.MariaDBDialect}
    hibernate:
      ddl-auto: update
    show-sql: true