### Notification Service

# @name Get User Notifications
GET http://localhost:8080/api/notifications/user/user123
Accept: application/json

###

# @name Test Create Notification
POST http://localhost:8080/api/notifications/test?userId=user123&message=Hello from IntelliJ HTTP Client
Accept: application/json

###

### Review Service

# @name Create Review
POST http://localhost:8080/api/reviews
Content-Type: application/json

{
    "rideId": "ride_001",
    "userId": "user123",
    "driverId": "driver456",
    "rating": 5,
    "comment": "Excellent ride! Smooth driving."
}

###

# @name Get Driver Reviews
GET http://localhost:8080/api/reviews/driver/driver456
Accept: application/json

###

# @name Get User Reviews
GET http://localhost:8080/api/reviews/user/user123
Accept: application/json
