services:
  notification-service:
    build:
      context: ..
      dockerfile: ./notification-service/Dockerfile
    container_name: notification-service
    ports:
      - "${NOTIFICATION_SERVICE_PORT:-8085}:${NOTIFICATION_SERVICE_PORT:-8085}"
    env_file:
      - ../.env
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - EUREKA_INSTANCE_INSTANCE_ID=notification-service:${NOTIFICATION_SERVICE_PORT:-8085}:$${random.value}
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/notification_db
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS:-kafka:9092}
    volumes:
      - maven-cache:/root/.m2
    networks:
      - cab-network
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
      mongodb:
        condition: service_started
      kafka:
        condition: service_healthy
    restart: on-failure

volumes:
  maven-cache:
    driver: local

networks:
  cab-network:
    driver: bridge
